version: '3.5'
services:
  postgresserver:
    image: postgres:alpine
    container_name: postgresserver
    hostname: postgres-server
    restart: always
    ports:
      - "4444:5432"
    environment:
      POSTGRES_DB: wymj_db_test
      POSTGRES_USER: wymj
      POSTGRES_PASSWORD: 123456
      PGPORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
        #command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    command: 
      -c ssl=off
      -c ssl_cert_file=/var/lib/postgresql/server.crt 
      -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./server.crt:/var/lib/postgresql/server.crt
      - ./server.key:/var/lib/postgresql/server.key
